# src/strategies/base.py

from abc import ABC, abstractmethod
import pandas as pd


class Strategy:
    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def process_data(
        self,
        market_data: dict[str, pd.DataFrame | pd.Series],
        options_positions: pd.DataFrame,
    ) -> pd.DataFrame | None:
        """
        Called by engine to generate signals and update current positions from market data.

        Returns a dataframe of orders and updates to be passed to the portfolio.
        """
        pass

    @abstractmethod
    def create_order(
        self, action: str, quantity: int, spot: float, option_row: pd.Series
    ) -> pd.Series:
        """
        Create standardized order row for the order dataframe generated by process_data().
        """
        order_row = option_row.copy()
        order_row["strike_price"] = order_row["strike_price"] / 1000
        order_row = pd.concat(
            [
                pd.Series({"action": action, "quantity": quantity, "spot": spot}),
                order_row,
            ]
        )
        return order_row
