# src/strategies/base.py

from abc import ABC, abstractmethod
import pandas as pd


class Strategy:
    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def process_data(
        self,
        market_data: dict[str, pd.DataFrame],
        options_positions: pd.Series,
    ) -> pd.DataFrame | None:
        """
        Called by engine to generate signals and update current positions from market data.

        Returns a dataframe of orders and updates to be passed to the portfolio.
        """
        pass

    @abstractmethod
    def create_order(self, action: str, option_row: pd.Series) -> pd.Series:
        """
        Create standardized order row for the order dataframe generated by process_data().
        """
        order_row = option_row.copy()
        order_row = pd.concat([pd.Series({"action": action}), order_row])
        return order_row
